#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Compare eddy_identify baseline CSV outputs.

This script is read-only. It does NOT run eddy detection and does NOT modify
any algorithm file. It compares either:

1. two summary CSV files generated by scripts/summarize_eddy_json.py; or
2. two per-eddy records CSV files generated by scripts/summarize_eddy_json.py.

Typical summary comparison:

    python scripts/compare_eddy_baseline.py summary \
        baseline_summary.csv new_summary.csv

Typical records comparison:

    python scripts/compare_eddy_baseline.py records \
        baseline_records.csv new_records.csv \
        --match-distance-deg 0.25 \
        --out-csv eddy_record_comparison.csv
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


Record = Dict[str, Any]


SUMMARY_NUMERIC_FIELDS = [
    "total_entries",
    "detected_eddies",
    "seed_only_entries",
    "anticyclonic_eddies",
    "cyclonic_eddies",
    "mean_radius",
    "median_radius",
    "mean_amplitude",
    "median_amplitude",
    "mean_Uavg_max",
    "mean_EKE",
]


RECORD_NUMERIC_FIELDS = [
    "core_lon",
    "core_lat",
    "core_sla",
    "radius_preferred",
    "amplitude_preferred",
    "eddy_effect_radius",
    "eddy_shape_radius",
    "eddy_Uavg_radius",
    "eddy_effect_amp",
    "eddy_shape_amp",
    "eddy_Uavg_amp",
    "eddy_Uavg_max",
    "eddy_effect_eke",
    "eddy_Uavg_eke",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare read-only baseline CSV outputs from eddy_identify."
    )
    subparsers = parser.add_subparsers(dest="mode", required=True)

    summary = subparsers.add_parser("summary", help="Compare two summary CSV files.")
    summary.add_argument("baseline_summary", type=Path)
    summary.add_argument("new_summary", type=Path)
    summary.add_argument(
        "--tolerance",
        type=float,
        default=1.0e-9,
        help="Absolute tolerance for numeric comparison. Default: 1e-9.",
    )
    summary.add_argument(
        "--out-csv",
        type=Path,
        default=None,
        help="Optional output CSV for field-by-field comparison.",
    )

    records = subparsers.add_parser("records", help="Compare two per-eddy records CSV files.")
    records.add_argument("baseline_records", type=Path)
    records.add_argument("new_records", type=Path)
    records.add_argument(
        "--match-distance-deg",
        type=float,
        default=0.25,
        help="Maximum same-sign core distance in degrees for matching eddies. Default: 0.25.",
    )
    records.add_argument(
        "--out-csv",
        type=Path,
        default=None,
        help="Optional output CSV for matched/new/missing eddies.",
    )
    records.add_argument(
        "--name-match-first",
        action="store_true",
        help="First match records with identical names before nearest-neighbor matching.",
    )
    return parser.parse_args()


def read_csv_rows(path: Path) -> List[Record]:
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        return [dict(row) for row in reader]


def read_one_row_csv(path: Path) -> Record:
    rows = read_csv_rows(path)
    if not rows:
        raise ValueError(f"CSV has no data rows: {path}")
    if len(rows) > 1:
        print(f"Warning: {path} has {len(rows)} rows; only the first row is used for summary comparison.")
    return rows[0]


def to_float(value: Any) -> Optional[float]:
    if value is None:
        return None
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        number = float(value)
        return number if math.isfinite(number) else None
    text = str(value).strip()
    if not text:
        return None
    try:
        number = float(text)
    except ValueError:
        return None
    return number if math.isfinite(number) else None


def format_value(value: Any) -> str:
    if value is None:
        return ""
    return str(value)


def compare_summary(args: argparse.Namespace) -> int:
    baseline = read_one_row_csv(args.baseline_summary)
    new = read_one_row_csv(args.new_summary)

    fields = sorted(set(baseline.keys()) | set(new.keys()))
    rows: List[Record] = []
    different_count = 0

    for field in fields:
        b_raw = baseline.get(field, "")
        n_raw = new.get(field, "")
        b_num = to_float(b_raw)
        n_num = to_float(n_raw)

        if b_num is not None and n_num is not None:
            diff = n_num - b_num
            abs_diff = abs(diff)
            same = abs_diff <= args.tolerance
            rel_diff = diff / b_num if b_num not in (0, None) else None
        else:
            diff = ""
            abs_diff = ""
            rel_diff = ""
            same = str(b_raw) == str(n_raw)

        if not same:
            different_count += 1

        rows.append(
            {
                "field": field,
                "baseline": b_raw,
                "new": n_raw,
                "difference": diff,
                "absolute_difference": abs_diff,
                "relative_difference": rel_diff,
                "same": same,
            }
        )

    print("Summary comparison")
    print("------------------")
    print(f"baseline_summary: {args.baseline_summary}")
    print(f"new_summary     : {args.new_summary}")
    print(f"different_fields: {different_count}")

    important_fields = [field for field in SUMMARY_NUMERIC_FIELDS if field in fields]
    if important_fields:
        print("\nImportant fields:")
        for row in rows:
            if row["field"] in important_fields:
                marker = "OK" if row["same"] else "DIFF"
                print(
                    f"[{marker}] {row['field']}: "
                    f"baseline={row['baseline']} new={row['new']} diff={row['difference']}"
                )

    if args.out_csv:
        write_csv(args.out_csv, rows, [
            "field",
            "baseline",
            "new",
            "difference",
            "absolute_difference",
            "relative_difference",
            "same",
        ])
        print(f"\nWrote comparison CSV: {args.out_csv}")

    return 0 if different_count == 0 else 1


def normalize_sign(value: Any) -> str:
    text = str(value or "").strip().lower()
    if text.startswith("anti") or text in {"ae", "a", "anticyclonic", "anticyclone"}:
        return "Anticyclonic"
    if text.startswith("cycl") or text in {"ce", "c", "cyclonic", "cyclone"}:
        return "Cyclonic"
    return str(value or "Unknown").strip() or "Unknown"


def get_xy(record: Record) -> Optional[Tuple[float, float]]:
    lon = to_float(record.get("core_lon"))
    lat = to_float(record.get("core_lat"))
    if lon is None or lat is None:
        return None
    return lon, lat


def distance_deg(a: Record, b: Record) -> Optional[float]:
    xy_a = get_xy(a)
    xy_b = get_xy(b)
    if xy_a is None or xy_b is None:
        return None
    lon_a, lat_a = xy_a
    lon_b, lat_b = xy_b

    # Handle 0/360 wrap approximately in degree space.
    dlon = abs(lon_a - lon_b)
    dlon = min(dlon, abs(dlon - 360.0))
    dlat = abs(lat_a - lat_b)
    return math.sqrt(dlon * dlon + dlat * dlat)


def record_id(record: Record, prefix: str) -> str:
    name = str(record.get("name") or "").strip()
    sign = normalize_sign(record.get("sign_type"))
    lon = record.get("core_lon", "")
    lat = record.get("core_lat", "")
    return f"{prefix}:{name}:{sign}:{lon}:{lat}"


def match_by_name(
    baseline: List[Record],
    new: List[Record],
    used_new: set,
) -> List[Tuple[Record, Record, float, str]]:
    matches: List[Tuple[Record, Record, float, str]] = []
    by_key: Dict[Tuple[str, str], List[int]] = {}
    for idx, record in enumerate(new):
        key = (str(record.get("name") or ""), normalize_sign(record.get("sign_type")))
        by_key.setdefault(key, []).append(idx)

    for b in baseline:
        key = (str(b.get("name") or ""), normalize_sign(b.get("sign_type")))
        candidates = by_key.get(key, [])
        for idx in candidates:
            if idx not in used_new:
                dist = distance_deg(b, new[idx])
                matches.append((b, new[idx], dist if dist is not None else float("nan"), "name"))
                used_new.add(idx)
                break
    return matches


def match_by_nearest(
    baseline: List[Record],
    new: List[Record],
    already_matched_baseline_ids: set,
    used_new: set,
    max_distance_deg: float,
) -> Tuple[List[Tuple[Record, Record, float, str]], List[Record]]:
    matches: List[Tuple[Record, Record, float, str]] = []
    missing: List[Record] = []

    for b in baseline:
        b_id = record_id(b, "baseline")
        if b_id in already_matched_baseline_ids:
            continue

        b_sign = normalize_sign(b.get("sign_type"))
        best_idx: Optional[int] = None
        best_dist: Optional[float] = None

        for idx, n in enumerate(new):
            if idx in used_new:
                continue
            if normalize_sign(n.get("sign_type")) != b_sign:
                continue
            dist = distance_deg(b, n)
            if dist is None:
                continue
            if dist <= max_distance_deg and (best_dist is None or dist < best_dist):
                best_idx = idx
                best_dist = dist

        if best_idx is None or best_dist is None:
            missing.append(b)
        else:
            used_new.add(best_idx)
            matches.append((b, new[best_idx], best_dist, "nearest"))

    return matches, missing


def compare_records(args: argparse.Namespace) -> int:
    baseline = read_csv_rows(args.baseline_records)
    new = read_csv_rows(args.new_records)

    # Keep only detected eddies when the field exists. If the field is absent, keep all rows.
    baseline = [r for r in baseline if str(r.get("is_detected", "True")).lower() not in {"false", "0", "no"}]
    new = [r for r in new if str(r.get("is_detected", "True")).lower() not in {"false", "0", "no"}]

    used_new: set = set()
    matches: List[Tuple[Record, Record, float, str]] = []

    if args.name_match_first:
        name_matches = match_by_name(baseline, new, used_new)
        matches.extend(name_matches)

    already_matched_baseline_ids = {record_id(match[0], "baseline") for match in matches}
    nearest_matches, missing = match_by_nearest(
        baseline=baseline,
        new=new,
        already_matched_baseline_ids=already_matched_baseline_ids,
        used_new=used_new,
        max_distance_deg=args.match_distance_deg,
    )
    matches.extend(nearest_matches)

    new_only = [record for idx, record in enumerate(new) if idx not in used_new]

    rows: List[Record] = []
    for b, n, dist, method in matches:
        row: Record = {
            "status": "matched",
            "match_method": method,
            "distance_deg": dist,
            "baseline_name": b.get("name", ""),
            "new_name": n.get("name", ""),
            "baseline_sign_type": normalize_sign(b.get("sign_type")),
            "new_sign_type": normalize_sign(n.get("sign_type")),
        }
        for field in RECORD_NUMERIC_FIELDS:
            b_num = to_float(b.get(field))
            n_num = to_float(n.get(field))
            row[f"baseline_{field}"] = b.get(field, "")
            row[f"new_{field}"] = n.get(field, "")
            if b_num is not None and n_num is not None:
                row[f"diff_{field}"] = n_num - b_num
            else:
                row[f"diff_{field}"] = ""
        rows.append(row)

    for b in missing:
        rows.append(
            {
                "status": "missing_in_new",
                "match_method": "",
                "distance_deg": "",
                "baseline_name": b.get("name", ""),
                "new_name": "",
                "baseline_sign_type": normalize_sign(b.get("sign_type")),
                "new_sign_type": "",
                "baseline_core_lon": b.get("core_lon", ""),
                "baseline_core_lat": b.get("core_lat", ""),
                "baseline_radius_preferred": b.get("radius_preferred", ""),
                "baseline_amplitude_preferred": b.get("amplitude_preferred", ""),
            }
        )

    for n in new_only:
        rows.append(
            {
                "status": "new_only",
                "match_method": "",
                "distance_deg": "",
                "baseline_name": "",
                "new_name": n.get("name", ""),
                "baseline_sign_type": "",
                "new_sign_type": normalize_sign(n.get("sign_type")),
                "new_core_lon": n.get("core_lon", ""),
                "new_core_lat": n.get("core_lat", ""),
                "new_radius_preferred": n.get("radius_preferred", ""),
                "new_amplitude_preferred": n.get("amplitude_preferred", ""),
            }
        )

    print("Records comparison")
    print("------------------")
    print(f"baseline_records : {args.baseline_records}")
    print(f"new_records      : {args.new_records}")
    print(f"baseline_count   : {len(baseline)}")
    print(f"new_count        : {len(new)}")
    print(f"matched          : {len(matches)}")
    print(f"missing_in_new   : {len(missing)}")
    print(f"new_only         : {len(new_only)}")
    print(f"match_distance_deg: {args.match_distance_deg}")

    if args.out_csv:
        fieldnames = build_record_comparison_fieldnames(rows)
        write_csv(args.out_csv, rows, fieldnames)
        print(f"\nWrote records comparison CSV: {args.out_csv}")

    return 0 if not missing and not new_only else 1


def build_record_comparison_fieldnames(rows: Sequence[Record]) -> List[str]:
    preferred = [
        "status",
        "match_method",
        "distance_deg",
        "baseline_name",
        "new_name",
        "baseline_sign_type",
        "new_sign_type",
    ]
    rest: List[str] = []
    for row in rows:
        for key in row.keys():
            if key not in preferred and key not in rest:
                rest.append(key)
    return preferred + rest


def write_csv(path: Path, rows: List[Record], fieldnames: Sequence[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fieldnames})


def main() -> None:
    args = parse_args()
    if args.mode == "summary":
        raise SystemExit(compare_summary(args))
    if args.mode == "records":
        raise SystemExit(compare_records(args))
    raise ValueError(f"Unsupported mode: {args.mode}")


if __name__ == "__main__":
    main()
